# .github/workflows/claude.yml  ← jobs: より「上」に置く！
name: Claude Assistant

permissions:                # ルート階層
  id-token: write           # ★ OIDC には必須 ★
  contents: write           # PR へ push
  pull-requests: write      # PR 作成・Approve

on:
  issue_comment:
    types: [created]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}