name: Claude Assistant

# ❶ ルートに **permissions** を置く（jobs: の外）
permissions:
  id-token: write         # ← これが無いと OIDC 変数が生成されない
  contents: write         # PR へのコミット／push 用
  pull-requests: write    # PR 作成・Approve 用

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  claude-response:
    # ※ if: 〜 を使うならここ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4       # ← 無くても動くが差分取得に便利
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # github_token を明示するなら↓
          # github_token: ${{ secrets.GITHUB_TOKEN }}