name: Claude Assistant

# Claude がコードを書いて push するには write 権限 + OIDC が必要
permissions:
  contents: write
  pull-requests: write
  issues: write         # issue への返信もさせたい場合
  id-token: write       # OIDC で GitHub App トークンを取る

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-response:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest

    steps:
      # ① リポジトリを clone（必須！）
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 既存履歴も使うので全部取るのが安全

      # ② Claude Code Action を実行
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # github_token を **自前で用意していなければ指定不要**。
          # Claude GitHub App + OIDC で自動取得されます